import numpy as np
ones_array=np.ones((2,3))
zeros_array=np.zeros((2,3))
empty_array=np.empty((2,3))
print("ones:",ones_array)
print("zeros:",zeros_array)
print("empty:",empty_array)
arr=np.array([[1,2,3],[4,5,6]])
print("shape of array:",arr.shape)
reshaped=arr.reshape(3,2)
print("reshaped array:",reshaped)
arr1=np.array([1,2,3])
copy_arr1=arr1.copy()
view_arr1=arr1.view()
print("original:",arr1)
print("copy:",copy_arr1)
arr2=np.array([1,2])
arr3=np.array([3,4])
concatenated=np.concatenate((arr2,arr3))
arr4=np.array([5,2,9,1])
print("sorted array:",np.sort(arr4))